### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by Vaygrim** [WilliamEz/CustomDrones#1]
At present version 1.3.0 for Minecraft 1.10.2 has no config file, so there is no way to adjust settings. Namely, I want to revert your addition of the new 'Mini Drone' mobs that spawn. Is this possible?

**Comment by WilliamEz** [comment]
I haven't made a config file yet, but thanks for reminding me :D

**Comment by WilliamEz** [comment]
Added config in 1.4.0
