### ISSUE TITLE
[1.10.2] Server crash

### ISSUE THREAD

**Issue by kwpugh** [WilliamEz/CustomDrones#3]
Forge: 2029
Mod: CustomDrones-1.3.0-mc1.10.2.jar

crash reports: http://pastebin.com/raw/DLRLaP2W

**Comment by WilliamEz** [comment]
Thanks for the report,
I'll see to it right now

**Comment by WilliamEz** [comment]
This crash is fixed in 1.4.0
Please update to the latest version.
Thanks :D
