### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by Darkosto** [WilliamEz/CustomDrones#4]
I'm getting a crash while exploring in-game:

http://pastebin.com/0UXYzhkH

Mod Version: 1.4.0-1.10.2
MC Version: 1.10.2
Forge Version: 2038

Thanks for checking this out! 
Darkosto

**Comment by WilliamEz** [comment]
That is pretty odd, does that happen regularly for you?

**Comment by Darkosto** [comment]
This has been happening fairly regular for me the more I explore in the pack. I can keep testing to get a better idea of how often it will happen.

**Comment by WilliamEz** [comment]
Should be fixed in 1.5.0
