### ISSUE TITLE
Drone lost, it run away by its own...

### ISSUE THREAD

**Issue by jonabrv1965** [WilliamEz/CustomDrones#6]
Hi, to report the loss of three drones in very similar situation : I had being "transported" by those little guys, when suddenly they drop me to the ground and start to run away from me until the controller lost them... it does not matter what I did with the controller (I changed the mode to follow crosshair and go to pointing not to avail). The only thing I noted is that I was near a village (I don't know why but my world is full of village everywhere)

Lenovo Laptop G40 (A8 Radeon R5 2Gb, 16Gb RAM)
CustomDrones-1.4.0-mc1.10.2
forge-1.10.2-12.18.1.2069
MC 1.10.2

I've 52 mods in my own designed/private modpack, If needed can provide the list.

I guess a "locator" device/procedure/method (to locate those drones left elsewhere or running away ones) could be handy!

**Comment by CKTheUltimate** [comment]
The problem you mention doesn't happen on me(I also have many villages in my world),also I think a "locator" isn't necessary as there is already a camera function in the mod,you can simply turn on the camera and see where your drones are.You may also use the following function during transport to prevent 
BTW can you post the modpack on somewhere like dropbox or Minecraft CurseForge,I want to try it out.

**Comment by jonabrv1965** [comment]
Hi William, thank you for the quick response. At bottom the Mod list I'm using. I will try the camera trick!. It just happened to me yesterday again : the drone was carrying me (flying me :-)) when suddenly drop me and disappear (and was disconnected from the control intermediately), I fall flat to the ground (thanks god I use a very good armor). Using my jetpack (which is much slower that your drones!) I look for the drone in the height at I was dropped at the very same XYZ coords, but cannot find anything... It is weird...

08/26/16  09:50 AM    <DIR>          .
08/26/16  09:50 AM    <DIR>          ..
08/15/16  10:13 AM    <DIR>          1.10.2
08/15/16  09:49 AM            40,400 Adamantium Mod-1.6.2.jar.old
08/24/16  04:13 PM            43,861 Adamantium Mod-1.6.3.jar
08/09/16  01:41 PM         1,874,877 bdlib-1.12.0.2-mc1.10.2.jar
08/21/16  02:12 PM         9,246,660 BloodMagic-1.9.4-2.0.4-56.jar
08/14/16  10:14 AM         1,395,440 Calculator-1.9.4-3.1.0.jar.old
08/17/16  10:33 AM         1,395,299 Calculator-1.9.4-3.1.1.jar
08/15/16  09:50 PM            77,584 Chameleon-1.10-2.1.7.jar
08/12/16  10:14 PM            70,393 Chameleon-1.9.4-2.1.6.jar.old
08/11/16  05:13 PM           115,576 ChickenChunks-1.10.2-2.1.3.36-universal.jar
08/11/16  05:13 PM           152,006 CodeChickenCore-1.10.2-2.1.8.79-universal.jar
07/08/16  02:16 PM         2,490,248 CustomDrones-1.0.3-mc1.10.2.jar.old
08/23/16  12:05 AM         2,947,202 CustomDrones-1.4.0-mc1.10.2.jar
07/08/16  01:48 PM           826,230 deepresonance-1.9.4-1.2.0beta35.jar
08/14/16  11:52 AM            43,561 disenchanter-[1.9.4]1.3.jar
08/12/16  11:46 PM            45,761 disenchanter-[1.9.4]1.4.jar.bad
07/08/16  02:35 PM           437,799 ElecCore-1.9.4-1.5.292.jar
08/09/16  10:50 AM           380,960 elementaldimensions-0.0.1.jar
08/25/16  11:40 AM         2,662,966 elementaldimensions-0.0.3.jar.xxx
08/09/16  01:37 PM           452,419 EnderCore-1.10.2-0.4.1.47-beta.jar.old
08/23/16  04:10 PM           454,476 EnderCore-1.10.2-0.4.1.51-beta.jar
07/08/16  01:56 PM            67,869 endercrop-1.9.4-1.3.1.jar
08/23/16  03:45 PM         4,516,622 EnderIO-1.10.2-3.0.1.95_beta.jar.old
08/24/16  04:14 PM         4,516,599 EnderIO-1.10.2-3.0.1.96_beta.jar
08/11/16  05:12 PM           184,667 EnderStorage-1.10.2-2.1.3.72-universal.jar
08/20/16  11:37 PM           229,741 endertanks-1.10.0-1.4.1.jar
08/20/16  11:38 PM            99,461 enderthing-1.10.2-0.6.11.jar
08/17/16  10:38 AM           233,088 expandableBackpacks1.1.8.jar
08/20/16  06:03 PM           268,104 FluxNetworks-1.9.4-1.0.5.jar.nouse
08/18/16  09:24 PM           320,016 Gadgets_n_Goodies_mod_v1.1.4_mc_v1.10.2.jar
08/21/16  12:33 PM            64,665 GiacomosFoundry1.10.2-1.3.5.jar
08/21/16  09:56 PM           194,046 Guide-API-1.10.2-2.0.2-45.jar
08/15/16  10:13 AM    <DIR>          ic2
08/12/16  10:07 PM           331,860 jei_1.10.2-3.8.0.240.jar.old
08/20/16  07:04 PM           332,972 jei_1.10.2-3.9.0.244.jar
07/08/16  01:53 PM            17,276 LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar
07/08/16  02:45 PM         3,202,318 Mantle-1.10-0.10.3.jar
08/03/16  08:06 PM           257,016 mcjtylib-1.10-1.9.9.jar
08/11/16  09:21 AM           172,952 MCMultiPart-1.2.1-universal.jar
08/26/16  09:50 AM                 0 modlistAug262016.txt
07/08/16  01:34 PM           537,477 mod_voxelMap_1.6.15_for_1.10.2.litemod
07/08/16  02:07 PM           171,549 nethercore-1.10.2-2.0.2.jar
08/02/16  09:36 PM        11,961,792 OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
08/04/16  12:10 AM         1,757,438 OptiFine_1.10.2_HD_U_C2.jar
08/20/16  11:50 PM            30,538 PersistentBits-1.10.2-1.0.4.jar
08/09/16  10:22 AM         1,204,242 pressure-1.3.1.3-mc1.10.2.jar.useless
07/08/16  01:35 PM           253,634 quantumflux-1.9.4-2.0.7.jar
08/20/16  05:26 PM            70,992 QuantumStorage-1.9.4-3.1.2.jar
08/09/16  01:19 PM            18,061 rangedpumps-0.2.jar
08/08/16  01:40 PM           497,443 RebornCore-1.10.2-2.6.2.15-universal.jar
08/14/16  08:13 AM           609,413 refinedstorage-0.8.19.jar.old
08/18/16  09:09 PM           609,985 refinedstorage-0.8.20.jar
08/20/16  07:06 PM         2,659,869 rftools-1.10-5.16.jar.old
08/23/16  03:51 PM         2,661,094 rftools-1.10-5.17.jar.old
08/25/16  11:17 AM         2,660,545 rftools-1.10-5.18.jar
08/21/16  01:03 PM           322,681 shetiphiancore-1.10.0-3.3.0.jar
08/05/16  05:14 PM            61,324 simplegenerators-1.10-0.7.1a.jar.old
08/22/16  11:13 PM           101,954 simplegenerators-1.10.2-0.10.2b.jar
07/08/16  02:12 PM           201,673 SolarFluxReborn-1.10.2_0.4b.jar
08/17/16  10:34 AM         1,014,301 SonarCore-1.9.4-3.1.2.jar.old
08/20/16  06:04 PM         1,012,149 SonarCore-1.9.4-3.1.4.jar
08/17/16  10:32 AM           531,843 StorageDrawers-1.10.2-3.2.5.jar.old
08/20/16  07:02 PM           531,885 StorageDrawers-1.10.2-3.2.6.jar
08/05/16  03:23 PM           410,114 StorageNetwork-1.9.4-1.12.7.jar
08/18/16  09:13 PM           299,710 supercraftingframe-1.10.2-1.2.1.87.jar
08/04/16  12:27 AM         2,292,902 TConstruct-1.10-2.3.3a.jar
08/24/16  04:41 PM            87,701 usefulnullifiers-1.2.0.jar
08/05/16  07:22 PM           195,267 valkyrielib-1.10.2-0.10.2.jar
08/21/16  05:22 PM           262,545 vanillamagic-1.10.2-0.12.2.0.jar.old
08/23/16  03:48 PM           263,615 vanillamagic-1.10.2-0.13.0.0.jar.BAD
08/25/16  11:15 AM           285,108 vanillamagic-1.10.2-0.13.1.0.jar
08/17/16  10:47 AM         1,010,754 villagebox-1.10.2-0.5.0.jar
08/15/16  10:13 AM    <DIR>          VoxelMods
07/08/16  02:20 PM           544,490 Waila-1.7.0-B3_1.9.4.jar
08/23/16  04:11 PM         1,372,202 zz-backpacks 1.10.2 - 3.1.1.jar

**Comment by WilliamEz** [comment]
xD that wasn't me replying to you xD thanks that guy.
Well this is quite odd, but seems like it is a problem from player using.
Did you press "Shift" when being carried by the drone? By default that'll make the drone drop you.

**Comment by jonabrv1965** [comment]
Hi, it happened again, but I was able to get a very weird print screen, see attachment, pay attention to the Y axis... my drone felt to level -64... I don't think is a player failure, there is something wrong. I suspect it is related to chunk loading, I can reproduce this but sometimes cannot get evidence like this screen...

![capture](https://cloud.githubusercontent.com/assets/13445986/18032141/0a61c95e-6cc2-11e6-9fde-48e1ef42ecb2.JPG)

**Comment by WilliamEz** [comment]
It could be a chunk load problem if you fly too fast and into an unloaded chunk. But that should be a temporary problem only and the drone should be back at the right place when you reload the world.

**Comment by WilliamEz** [comment]
Can not reproduce the problem myself.
