### ISSUE TITLE
Server Crash Updating from 1.4.0-1.5.0

### ISSUE THREAD

**Issue by Towsty** [WilliamEz/CustomDrones#9]
World was generated on Drones 1.4.0. After updating to 1.5.0 the server crashes on player login. Crash Report and Server Log are attached.

I believe this is the same error that was reported on the forum, thought I would post it here for good measure.
Server Log:
[fml-server-latest.txt](https://github.com/WilliamEz/CustomDrones/files/443361/fml-server-latest.txt)
Crash Report:
[crash-2016-08-29_22.05.47-server.txt](https://github.com/WilliamEz/CustomDrones/files/443363/crash-2016-08-29_22.05.47-server.txt)

**Comment by WilliamEz** [comment]
This is already addressed and will be fixed in the next update.
Thanks for the report. Though next time please somehow send the crash by means that I won't have to download them.

**Comment by K4N0** [comment]
I'll try version 1.4.0
I am getting a similar or possibly the same crash upon world generation. I have just downloaded the mod. I am generating a new world. http://pastebin.com/0PL3wrTk
